[package]
name = "home-camera"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
anyhow = "1.0"
shiguredo_s3 = "2026.1.0-canary.0"

[dev-dependencies]
proptest = "1"
