apiVersion: v1
kind: Secret
metadata:
  name: home-camera-secret
  namespace: sandbox
type: Opaque
stringData:
  RTSP_URL: rtsp://user:password@camera.local:554/stream1
  AWS_ACCESS_KEY_ID: change-me
  AWS_SECRET_ACCESS_KEY: change-me
